services:
  traefik:
    image: traefik:v3.3
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"               # HTTP
      - "443:443"             # HTTPS
      - "8080:8080"           # Dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

networks:
  web:
    external: true