services:
  traefik:
    image: traefik:v2.10        # multi-arch, ARM compatible
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=chaumettetom@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --api.insecure=true        # dashboard activé en local
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"                # accès dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/letsencrypt:/letsencrypt
    networks:
      - web

networks:
  web:
    external: true