services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"               # HTTP
      - "443:443"             # HTTPS
      - "8080:8080"           # Dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  # --- Base de données centralisée ---
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    environment:
      # Place ces variables dans un fichier .env ou des secrets Docker
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql        # persistance des données
    networks:
      - web

  # --- Interface phpMyAdmin ---
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=128M
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`phpmyadmin.dev.localhost`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true